### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by nhantr** [Hydrothermal/better-pastebin#17]
```

/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/
cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/static.js:22:14)
    at Request._callback (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/better-pastebin/lib/better-pastebin.js:64:29)
    at self.callback (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/to
rula-cli/node_modules/request/request.js:188:22)
```

https://github.com/Hydrothermal/better-pastebin/blob/master/lib/better-pastebin.js#L64

_Originally posted by @ralyodio in https://github.com/Hydrothermal/better-pastebin/issues/8#issuecomment-315818338_

**Comment by nhantr** [comment]
I tried to open the better-pastebin.js:64:29 and add console.log for error and found that the problem came from nodejs: **error self signed certificate in certificate chain**

fixed by add before calling API and it works now!!
`process.env.NODE_TLS_REJECT_UNAUTHORIZED='0';`
