### ISSUE TITLE
edit no longer works

### ISSUE THREAD

**Issue by am1stad** [Hydrothermal/better-pastebin#8]
Edit has been broken since March.

**Comment by Hydrothermal** [comment]
Fixed by 7432841ce1dc13b376129210cb07591448e8cdc0.

**Comment by chovy** [comment]
```

/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/
cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/static.js:22:14)
    at Request._callback (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/better-pastebin/lib/better-pastebin.js:64:29)
    at self.callback (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/to
rula-cli/node_modules/request/request.js:188:22)
```

**Comment by scottie** [comment]
Edit is broken

**Comment by nhantr** [comment]
> ```
> 
> /home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/
> cheerio/lib/parse.js:55
>     var oldParent = node.parent || node.root,
>                         ^
> 
> TypeError: Cannot read property 'parent' of undefined
>     at Function.exports.update (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/parse.js:55:25)
>     at module.exports (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/parse.js:17:11)
>     at Function.exports.load (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/cheerio/lib/static.js:22:14)
>     at Request._callback (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/example-cli/node_modules/better-pastebin/lib/better-pastebin.js:64:29)
>     at self.callback (/home/example/.nvm/versions/node/v7.3.0/lib/node_modules/to
> rula-cli/node_modules/request/request.js:188:22)
> ```
> 
> https://github.com/Hydrothermal/better-pastebin/blob/master/lib/better-pastebin.js#L64

please check #17
